name: Main

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    if: github.repository_owner == 'nightfallstorm'
    uses: adya/pack-skse-mod/.github/workflows/pack.yml@main
    with:
      CMAKE_VR_CONFIG_PRESET: ''
      CMAKE_VR_BUILD_PRESET: ''
      AE_353_BRANCH: master-1.6.353
      FOMOD_INCLUDE_PDB: true
      FOMOD_MOD_NAME: "Papyrus Tweaks"
      FOMOD_MOD_AUTHOR: "nightfallstorm"
      FOMOD_MOD_NEXUS_ID: "77779"
      FOMOD_REQUIRED_INSTALLATION_DIR: "Papyrus"
      PUBLISH_ARCHIVE_TYPE: '7z'